### PR TITLE
updated yml file

### PR DESCRIPTION
**Pull request by anjaliahlawat**

### CODE REVIEW

**Comment by anjaliahlawat** [comment]
I think the problem was that in workflow it couldn't fetch the amazon url form environment variables. Right?

**Comment by h2grover** [comment]
@anjaliahlawat  

> I think the problem was that in workflow it couldn't fetch the amazon url form environment variables. Right?

yes

**Review by h2grover — CHANGES_REQUESTED** [review]
@anjaliahlawat There is a better approach for the same. Please give it some time and think about it.

**Review by h2grover — CHANGES_REQUESTED** [review]
@anjaliahlawat what if we have multiple env variables which are static, will you do this for every env variable?

Let's add puppeteer timeout in the `env`  and use the same in the launch option 
https://devdocs.io/puppeteer/

**Comment by h2grover** [comment]
@anjaliahlawat please let me know what will you change before you start refactoring. Plz post your thoughts

**Comment by anjaliahlawat** [comment]
@h2grover Currently by default timeout is set for 30 secs in launch option. What should I change it to in our timeout env variable? Or should I disable it?

**Comment by h2grover** [comment]
@anjaliahlawat what will happen if you disable it?

**Comment by anjaliahlawat** [comment]
@h2grover When we provide timeout value, it is to wait for browser instance to start till that time. But if we pass 0, we are disabling it which means it will keep on waiting and hence avoiding any timeout errors.

**Comment by h2grover** [comment]
@anjaliahlawat so do you want to disable the timeout then? Need to know your thoughts.

**Comment by anjaliahlawat** [comment]
@h2grover I have read it somewhere that to load heavy page we may have to disable it. But in general scenario, we shouldn't disable it as we can't go on waiting forever and never knew about the bug , if there's a problem we must get to it on time.

**Comment by h2grover** [comment]
@anjaliahlawat right, so for page load we can pass timeout in the function and the timeout which we pass in the launch option is applicable to all. 
Lets use 40000 as our default timeout.

Lets create another PR for this (not now) and create new issue to keep track of this requirement.

**Review by h2grover — APPROVED** [review]

**Comment by h2grover** [comment]
@anjaliahlawat also please test your code on github action and post the URL of the job here

**Comment by anjaliahlawat** [comment]
@h2grover https://github.com/anjaliahlawat/amazon-login-script/runs/2163996492?check_suite_focus=true
One test is passed and one failed. Working on it now

**Comment by h2grover** [comment]
@anjaliahlawat please create a PR for the fix also for yml file if needed.

**Comment by anjaliahlawat** [comment]
@h2grover I don't think we need a pr for this but I will make one if you say so. It seems as if secret key set in github is not being read properly in code.

**Comment by h2grover** [comment]
@anjaliahlawat how about the changea you did in `actions` branch? Don't you think you have to update master according to that?

**Comment by anjaliahlawat** [comment]
@h2grover Of course, in that case I will. But I haven't made any significant changes in yml file.

**Comment by h2grover** [comment]
@anjaliahlawat
> But I haven't made any significant changes in yml file.

can you please about it for a moment?

your Github actions were throwing errors because `yml` file had a syntax error but you fixed it on `actions`. If you are not updating the `master` branch how we keep track of the latest code?

Let me know if you don't get this but please create a PR for the yml fix

**Comment by h2grover** [comment]
@anjaliahlawat have you create a new issue as per https://github.com/anjaliahlawat/amazon-login-script/pull/26#issuecomment-803806968 ? Please post the link here.

**Comment by anjaliahlawat** [comment]
@h2grover https://github.com/anjaliahlawat/amazon-login-script/projects/1#card-57409940

**Comment by h2grover** [comment]
@anjaliahlawat thanks for opening the issue but post this URL instead moving forward.

https://github.com/anjaliahlawat/amazon-login-script/issues/28

You can see this under `issues` tab

**Pull request merged**
